typography_spectrum: 1
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.23991282796487212
  lightness: 0.5622995255980641
  saturation: 0.08937171893194318
  rhythmicContrast: 0.5089177421759814
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
name: Vikash Kumar
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Home D
    id: 215845c4-781a-4a22-b759-c7cade9e69d3
    type: content
favicon: null
purpose: []
