typography_spectrum: 0.7695702179335058
color:
  brandColors:
    - '#332532'
    - '#644D52'
    - '#F77A52'
    - '#FF974F'
    - '#A49A87'
  brandStrength: 0.2087798782158643
  lightness: 0.34837990207597613
  saturation: 0.23008521948941052
  rhythmicContrast: 0.29439348680898547
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.03676042030565441
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: 'Vikash Kumar '
name: Vikash Kumar
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Home D
    id: 215845c4-781a-4a22-b759-c7cade9e69d3
    type: content
favicon: null
title: Candid Wedding Photography
purpose: []
